namespace FormCaptureLocalWasm.Models.DbModels;

/// <summary>
/// An abstract class that is a parent class of entity classes.
/// </summary>
public abstract class Entity
{
    /// <summary>
    /// Date of row creation.
    /// </summary>
    public DateTime Added { get; private set; }

    /// <summary>
    /// ID of a model. Generated by Guid.NewGuid().ToString() method.
    /// </summary>
    public string ID { get; set; }

    /// <summary>
    /// Date of last update.
    /// </summary>
    public DateTime Updated { get; set; }

    /// <summary>
    /// Method for setting date information during creation of an entity.
    /// </summary>
    public void SetDateAdded()
    {
        Added = DateTime.Now;
        Updated = Added;
    }
}