name: .NET

on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101
    - name: Instal wasm tools
      run: dotnet workload install wasm-tools
    - name: Restore dependencies
      run: dotnet restore ./src/FormCaptureLocalWasm/FormCaptureLocalWasm.sln
    - name: Build
      run: dotnet build ./src/FormCaptureLocalWasm/FormCaptureLocalWasm.sln --no-restore
    - name: Test
      run: dotnet test ./src/FormCaptureLocalWasm/FormCaptureLocalWasm.sln --no-build --verbosity normal
